### ISSUE TITLE
sweet.js compile-time macros? and Practical CL

### ISSUE THREAD

**Issue by omouse** [teesloane/macro-workshop#1]
hey have you seen [sweet.js](https://www.sweetjs.org/)?

## Practical Common Lisp
also the book Practical Common Lisp has two good sections on macros:

* [Macros: Standard Control Constructs](http://gigamonkeys.com/book/macros-standard-control-constructs.html)
* [Macros: Defining Your Own](http://gigamonkeys.com/book/macros-defining-your-own.html)

>The key to understanding macros is to be quite clear about the distinction between the code that generates code (macros) and the code that eventually makes up the program (everything else). When you write macros, you're writing programs that will be used by the compiler to generate the code that will then be compiled. Only after all the macros have been fully expanded and the resulting code compiled can the program actually be run. The time when macros run is called macro expansion time; this is distinct from runtime, when regular code, including the code generated by macros, runs.
>
>It's important to keep this distinction firmly in mind because code running at macro expansion time runs in a very different environment than code running at runtime. Namely, at macro expansion time, there's no way to access the data that will exist at runtime.

could be useful for the notes on macros and for replicating some of the examples from common lisp into clojurescript

**Comment by teesloane** [comment]
Hey @omouse I'm actually using sweet.js to do a workshop on macros in JS. I am still ironing out my own understanding of macros as it were; but thanks for the links -- I will investigate them more closely soon.

**Comment by omouse** [comment]
lmk when you have some more code up and how you're enjoying ClojureScript!

**Comment by teesloane** [comment]
Will do... I'm playing with using sweet.js to build a DSL for processing js for building a sort of 2d-tile building language haha. Need to write more code fasterfasterfaster!

Will get back to CLJS soon and keep you in the loop!

**Comment by omouse** [comment]
haha, nice, I tried out [sweet.js with three.js, a webgl library](https://neverfriday.com/2014/07/02/sweet-js-macro-for-three-js-webgl/) and I wrote [an emacs mode for Processing](https://github.com/ptrv/processing2-emacs) (not processing js) back in the day. Funny how people gravitate toward processing for graphics, such a nice API.

**Comment by teesloane** [comment]
Woah, too funny. I was playing around with basically the same thing with macros and three.js. I ended up getting a little lost in the three.js api, and, realizing that all of this will be easier in 2D ha. 

Ideally, I'll end up with creating a dsl that allows creating syntax something like this:

`(square above square) below (square rightOf square)`

Right now I'm building this out without macros and then looking at how I can use macros to create these sort of infix functions that will eventually allow building this: 

![pasted_image_at_2017_09_03_05_26_pm](https://user-images.githubusercontent.com/12987958/30081388-f85c58d2-9254-11e7-9176-67394ed90bb6.png)

without having to write code [like this](https://github.com/teesloane/macro-workshop/blob/master/dist/p5-scratch.js#L66).

Really cool about the processing mode. On a slightly related note; I hope someday to get into doing more stuff with processing, but using [quil](https://github.com/quil/quil) so I can get better at writing clojure / lisp along the way.
